name: PlayerVsHunter
version: ${project.version}
main: com.bradyvolkmann.playervshunter.PlayerVsHunter
api-version: 1.13
commands:
  sethunter:
    description: Sets the hunter player
    usage: /sethunter [player]
    permission: PlayerVsHunter.sethunter
    permission-message: You don't have permission
  setrunner:
    description: Sets the runner player
    usage: /setrunner [player]
    permission: PlayerVsHunter.setrunner
    permission-message: You don't have permission
  startgame:
    description: Starts the player vs hunter game
    usage: /startgame
    permission: PlayerVsHunter.startgame
    permission-message: You don't have permission
